# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-25 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('times', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=25)),
                ('room', models.CharField(max_length=100)),
                ('dates', models.CharField(max_length=50)),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
